<a href="https://colab.research.google.com/github/Hubert26/suicides_IPPAN/blob/main/data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [139]:
import pandas as pd
import numpy as np
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive
import os
from google.colab import files

#Ustawienie braku maksymalnej ilości wyświetlanych kolumn
pd.options.display.max_columns = None

# 2023

In [140]:
df_raw_2023 = pd.read_excel('https://raw.githubusercontent.com/Hubert26/suicides_IPPAN/main/data/Samobojstwa_2023.xlsx')

In [141]:
df_raw_2023.head(5)

ID samobójcy    Data rejestracji Przedział wiekowy       Płeć  \
0    138421942 2023-01-01 01:15:42             25-29  Mężczyzna   
1    138421944 2023-01-01 01:32:02             55-59  Mężczyzna   
2    138421949 2023-01-01 01:54:15             13-18    Kobieta   
3    138421953 2023-01-01 02:19:35             55-59  Mężczyzna   
4    138421954 2023-01-01 02:32:52             19-24    Kobieta   

          Stan cywilny            Wykształcenie Informacje o pracy i nauce  \
0  Konkubent/konkubina  Brak danych/nieustalone                 Bezrobotny   
1       Żonaty/zamężna  Brak danych/nieustalone    Brak danych/nieustalono   
2        Kawaler/panna  Brak danych/nieustalone                      Uczeń   
3       Żonaty/zamężna  Brak danych/nieustalone    Brak danych/nieustalono   
4  Konkubent/konkubina  Brak danych/nieustalone    Brak danych/nieustalono   

           Źródło utrzymania Czy samobójstwo zakończyło się zgonem  \
0    Brak danych/nieustalony                                     N   
1    Brak danych/nieustalony                                     N   
2  Na utrzymaniu innej osoby                                     N   
3    Brak danych/nieustalony                                     N   
4    Brak danych/nieustalony                                     N   

  Miejsce zamachu                           Klasa miejscowości  \
0  Mieszkanie/dom                                         Wieś   
1  Mieszkanie/dom    Miasto o liczbie ludności 20 000 – 49 999   
2  Mieszkanie/dom                                         Wieś   
3  Mieszkanie/dom          Miasto o liczbie ludności do 19 999   
4  Mieszkanie/dom  Miasto o liczbie ludności 100 000 – 499 999   

              Sposób popełnienia                              Powód zamachu *  \
0  Samookaleczenie powierzchowne                   Inny niewymieniony powyżej   
1                Powieszenie się                                  Nieustalony   
2           Zażycie innych leków  Nieporozumienie rodzinne/przemoc w rodzinie   
3  Samookaleczenie powierzchowne  Nieporozumienie rodzinne/przemoc w rodzinie   
4           Zażycie innych leków             Konflikt z osobami spoza rodziny   

                               Powód zamachu 2 Powód zamachu 3  \
0  Nieporozumienie rodzinne/przemoc w rodzinie             NaN   
1                                          NaN             NaN   
2                                          NaN             NaN   
3                                          NaN             NaN   
4                                          NaN             NaN   

  Powód zamachu 4       Stan świadomości *  \
0             NaN     Pod wpływem alkoholu   
1             NaN  Brak danych/nieustalony   
2             NaN               Trzeźwy(a)   
3             NaN     Pod wpływem alkoholu   
4             NaN     Pod wpływem alkoholu   

  Informacje dotyczące stanu zdrowia *  \
0              Brak danych/nieustalono   
1              Brak danych/nieustalono   
2              Brak danych/nieustalono   
3                Nadużywał(a) alkoholu   
4                Nadużywał(a) alkoholu   

  Informacje dotyczące leczenia z powodu alkoholizmu/narkomanii  \
0                                                NaN              
1                                                NaN              
2                                                NaN              
3                                                NaN              
4                                                NaN              

  W ciągu ostatniego miesiąca sprawca zdarzenia miał przynajmniej jeden raz kontakt z *  
0                          Brak możliwości ustalenia                                     
1                          Brak możliwości ustalenia                                     
2                                 Placówką leczniczą                                     
3                          Brak możliwości ustalenia                                     
4                          Brak możliwości us

##Zamiana nazw kolumn

In [142]:
# Zamiana spacji na podkreślenia w nazwach kolumn
df_raw_2023.rename(columns=lambda x: x.replace(' ', '_'), inplace=True)


In [143]:
df_raw_2023.rename(columns={'Data_rejestracji': 'Date'}, inplace=True)

## Daty

In [144]:
# Wyodrębnienie roku i miesiąca
df_raw_2023['Date'] = pd.to_datetime(df_raw_2023['Date'])
df_raw_2023['DateY'] = df_raw_2023['Date'].dt.strftime('%Y')
df_raw_2023['DateM'] = df_raw_2023['Date'].dt.strftime('%m')

In [145]:
df_raw_2023['DateY'].unique()

array(['2023', nan], dtype=object)

In [146]:
df_raw_2023['DateM'].unique()

array(['01', '02', nan, '03', '04', '05', '06', '07', '08', '09', '10',
       '11', '12'], dtype=object)

In [147]:
# Połączenie roku i miesiąca w formacie MM.YYYY
df_raw_2023['Date'] = df_raw_2023['DateM'] + '.' + df_raw_2023['DateY']

In [148]:
df_raw_2023['Date'].unique()

array(['01.2023', '02.2023', nan, '03.2023', '04.2023', '05.2023',
       '06.2023', '07.2023', '08.2023', '09.2023', '10.2023', '11.2023',
       '12.2023'], dtype=object)

##Mapowanie

###Przedział_wiekowy

In [149]:
column = 'Przedział_wiekowy'
df_raw_2023.rename(columns={column: 'Age1'}, inplace=True)

In [150]:
df_raw_2023['Age1'].unique()

array(['25-29', '55-59', '13-18', '19-24', '30-34', '50-54', '40-44',
       '45-49', '35-39', '65-69', '75-79', '80-84', '60-64', '70-74',
       '85+', '7-12', 'Nieustalony wiek', nan], dtype=object)

In [151]:
column = 'Age1'
mapping = {
    "7-12": '07-12',
    '13-18': '13-18',
    '19-24': '19-24',
    '25-29': '25-29',
    '30-34': '30-34',
    '35-39': '35-39',
    '40-44': '40-44',
    '45-49': '45-49',
    '50-54': '50-54',
    '55-59': '55-59',
    '60-64': '60-64',
    '65-69': '65-69',
    '70-74': '70-74',
    '75-79': '75-79',
    '80-84': '80-84',
    '85+': '85+',
    'Nieustalony wiek': np.nan
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)


In [152]:
df_raw_2023['Age2'] = df_raw_2023['Age1']

In [153]:
df_raw_2023['Age2'].unique()

array(['25-29', '55-59', '13-18', '19-24', '30-34', '50-54', '40-44',
       '45-49', '35-39', '65-69', '75-79', '80-84', '60-64', '70-74',
       '85+', '07-12', nan], dtype=object)

In [154]:
column = 'Age2'
mapping = {
    "07-12": '00-18',
    '13-18': '00-18',
    '19-24': '19-34',
    '25-29': '19-34',
    '30-34': '19-34',
    '35-39': '35-64',
    '40-44': '35-64',
    '45-49': '35-64',
    '50-54': '35-64',
    '55-59': '35-64',
    '60-64': '35-64',
    '65-69': '65+',
    '70-74': '65+',
    '75-79': '65+',
    '80-84': '65+',
    '85+': '65+'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)


###Płeć

In [155]:
df_raw_2023['Płeć'].unique()

array(['Mężczyzna', 'Kobieta', nan], dtype=object)

In [156]:
df_raw_2023.rename(columns={'Płeć': 'Gender'}, inplace=True)

In [157]:
column = 'Gender'
mapping = {
    "Kobieta": 'F',
    "Mężczyzna": 'M'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)


In [158]:
df_raw_2023['Gender'].unique()

array(['M', 'F', nan], dtype=object)

###Stan_cywilny

In [159]:
df_raw_2023['Stan_cywilny'].unique()

array(['Konkubent/konkubina', 'Żonaty/zamężna', 'Kawaler/panna',
       'Brak danych/nieustalony', 'Rozwiedziony/rozwiedziona',
       'Wdowiec/wdowa', 'Separowany/separowana', nan], dtype=object)

In [160]:
column = 'Stan_cywilny'
mapping = {
    "Brak danych/nieustalony": np.nan,
    "Kawaler/panna": 'Single ',
    "Konkubent/konkubina": 'Cohabitant',
    "Żonaty/zamężna": 'Married',
    "Separowany/separowana": 'Separated',
    "Rozwiedziony/rozwiedziona": 'Divorced',
    "Wdowiec/wdowa": 'Widowed'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Marital'}, inplace=True)


In [161]:
df_raw_2023['Marital'].unique()

array(['Cohabitant', 'Married', 'Single ', nan, 'Divorced', 'Widowed',
       'Separated'], dtype=object)

###Wykształcenie

In [162]:
df_raw_2023['Wykształcenie'].unique()

array(['Brak danych/nieustalone', 'Podstawowe', 'Średnie',
       'Zasadnicze zawodowe', 'Podstawowe niepełne', 'Wyższe',
       'Gimnazjalne', 'Policealne', nan], dtype=object)

In [163]:
column = 'Wykształcenie'
mapping = {
    'Brak danych/nieustalone': np.nan,
    'Podstawowe niepełne': 'Pre-primary',
    'Podstawowe': 'Primary',
    'Gimnazjalne': 'Secondary',
    'Zasadnicze zawodowe': 'Vocational',
    'Średnie': 'Secondary',
    'Policealne': 'Secondary',
    'Wyższe': 'Higher'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Education'}, inplace=True)



In [164]:
df_raw_2023['Education'].unique()

array([nan, 'Primary', 'Secondary', 'Vocational', 'Pre-primary', 'Higher'],
      dtype=object)

###Informacje_o_pracy_i_nauce

In [165]:
df_raw_2023['Informacje_o_pracy_i_nauce'].unique()

array(['Bezrobotny', 'Brak danych/nieustalono', 'Uczeń', 'Praca stała',
       'Rolnik', 'Praca dorywcza', 'Student',
       'Pracujący na własny rachunek/samodzielna działalność gospodarcza',
       nan], dtype=object)

In [166]:
column = 'Informacje_o_pracy_i_nauce'
mapping = {
    'Brak danych/nieustalono': np.nan,
    'Uczeń': 'Student',
    'Student': 'Student',
    'Rolnik': 'Agriculturalist',
    'Pracujący na własny rachunek/samodzielna działalność gospodarcza': 'Employed',
    'Praca stała': 'Employed',
    'Praca dorywcza': 'Employed',
    'Bezrobotny': 'Unemployed'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'WorkInfo'}, inplace=True)

In [167]:
df_raw_2023['WorkInfo'].unique()

array(['Unemployed', nan, 'Student', 'Employed', 'Agriculturalist'],
      dtype=object)

###Źródło_utrzymania

In [168]:
df_raw_2023['Źródło_utrzymania'].unique()

array(['Brak danych/nieustalony', 'Na utrzymaniu innej osoby', 'Praca',
       'Emerytura', 'Nie ma stałego źródła utrzymania', 'Renta',
       'Zasiłek/alimenty', nan], dtype=object)

In [169]:
column = 'Źródło_utrzymania'
mapping = {
    'Brak danych/nieustalony': np.nan,
    'Na utrzymaniu innej osoby': 'Dependent',
    'Praca': 'Steady',
    'Emerytura': 'Benefits',
    'Renta': 'Benefits',
    'Zasiłek/alimenty': 'Benefits',
    'Nie ma stałego źródła utrzymania': 'NoSteady'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Income'}, inplace=True)

In [170]:
df_raw_2023['Income'].unique()

array([nan, 'Dependent', 'Steady', 'Benefits', 'NoSteady'], dtype=object)

###Czy_samobójstwo_zakończyło_się_zgonem

In [171]:
df_raw_2023['Czy_samobójstwo_zakończyło_się_zgonem'].unique()

array(['N', 'T', nan], dtype=object)

In [172]:
column = 'Czy_samobójstwo_zakończyło_się_zgonem'

mapping = {
    'T': 1,
    'N': 0
}
df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Fatal'}, inplace=True)

In [173]:
df_raw_2023['Fatal'].unique()

array([ 0.,  1., nan])

###Miejsce_zamachu

In [174]:
df_raw_2023['Miejsce_zamachu'].unique()

array(['Mieszkanie/dom', 'Rzeka/jezioro/inny zbiornik wodny',
       'Zabudowania gospodarcze', 'Garaż/piwnica/strych',
       'Droga/ulica/chodnik', 'Teren kolei/tory', 'Park, las', 'Inne',
       'Szkoła/uczelnia', 'Zakład pracy',
       'Placówka wychowawczo-opiekuńcza',
       'Placówka lecznicza lub sanatoryjna', 'Miejsce prawnej izolacji',
       'Obiekt policyjny', 'Obiekt wojskowy', nan], dtype=object)

In [175]:
column = 'Miejsce_zamachu'
mapping = {
    'Droga/ulica/chodnik': 'Road',
    'Zabudowania gospodarcze': 'UtilitySpaces',
    'Mieszkanie/dom': 'House',
    'Teren kolei/tory': 'Railway',
    'Park, las': 'Forest',
    'Garaż/piwnica/strych': 'House',
    'Rzeka/jezioro/inny zbiornik wodny': 'WaterRes',
    'Zakład pracy': 'Work',
    'Placówka lecznicza lub sanatoryjna': 'Institution',
    'Miejsce prawnej izolacji': 'Isolation',
    'Obiekt wojskowy': 'PoliceArmy',
    'Placówka wychowawczo-opiekuńcza': 'Institution',
    'Szkoła/uczelnia': 'School',
    'Obiekt policyjny': 'PoliceArmy',
    'Inne': 'Other'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Place'}, inplace=True)


In [176]:
df_raw_2023['Place'].unique()

array(['House', 'WaterRes', 'UtilitySpaces', 'Road', 'Railway', 'Forest',
       'Other', 'School', 'Work', 'Institution', 'Isolation',
       'PoliceArmy', nan], dtype=object)

###Sposób_popełnienia

In [177]:
df_raw_2023['Sposób_popełnienia'].unique()

array(['Samookaleczenie powierzchowne', 'Powieszenie się',
       'Zażycie innych leków',
       'Zażycie środków nasennych/leków psychotropowych',
       'Uszkodzenie układu krwionośnego', 'Inny',
       'Utonięcie/utopienie się', 'Rzucenie się pod pojazd w ruchu',
       'Uduszenie się', 'Rzucenie się z wysokości',
       'Zastrzelenie się/użycie broni palnej', 'Zatrucie gazem/spalinami',
       'Samopodpalenie', 'Zatrucie środkami chemicznymi/toksycznymi',
       'Zatrucie środkami odurzającymi', 'Zatrucie dopalaczami', nan],
      dtype=object)

In [178]:
column = 'Sposób_popełnienia'
mapping = {
    'Rzucenie się pod pojazd w ruchu': 'Vehicle',
    'Rzucenie się z wysokości': 'Jumping',
    'Powieszenie się': 'Hanging',
    'Uszkodzenie układu krwionośnego': 'Self-harm',
    'Zastrzelenie się/użycie broni palnej': 'Schooting',
    'Samookaleczenie powierzchowne': 'Self-harm',
    'Zażycie środków nasennych/leków psychotropowych': 'Drugs',
    'Zatrucie gazem/spalinami': 'Gas',
    'Zażycie innych leków': 'Drugs',
    'Zatrucie środkami chemicznymi/toksycznymi': 'Poisoning',
    'Zatrucie środkami odurzającymi': 'Drugs',
    'Zatrucie dopalaczami': 'Drugs',
    'Utonięcie/utopienie się': 'Drowning',
    'Samopodpalenie': 'Self-harm',
    'Uduszenie się': 'Other',
    'Inny': 'Other'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Method'}, inplace=True)

In [179]:
df_raw_2023['Method'].unique()

array(['Self-harm', 'Hanging', 'Drugs', 'Other', 'Drowning', 'Vehicle',
       'Jumping', 'Schooting', 'Gas', 'Poisoning', nan], dtype=object)

###Powód_zamachu

In [180]:
list(set(df_raw_2023['Powód_zamachu_*'].unique()) | set(df_raw_2023['Powód_zamachu_2'].unique()) | set(df_raw_2023['Powód_zamachu_3'].unique()) | set(df_raw_2023['Powód_zamachu_4'].unique()))

['Trwałe kalectwo',
 'Dokonanie przestępstwa lub wykroczenia',
 'Konflikt z osobami spoza rodziny',
 'Nagła utrata źródła utrzymania',
 'Zawód miłosny',
 'Leczony(a) psychiatrycznie',
 'Inny niewymieniony powyżej',
 'Choroba psychiczna/zaburzenia psychiczne',
 'Choroba fizyczna',
 'Niepożądana ciąża',
 'Problemy w szkole lub pracy',
 nan,
 'Nieporozumienie rodzinne/przemoc w rodzinie',
 'Pogorszenie lub nagła utrata zdrowia',
 'Zagrożenie lub utrata miejsca zamieszkania',
 'Nieustalony',
 'Złe warunki ekonomiczne/długi',
 'Nosiciel wirusa HIV, chory na AIDS',
 'Mobbing, cybermobbing, znęcanie',
 'Śmierć bliskiej osoby']

In [181]:
column = 'Powód_zamachu_*'
mapping = {
    'Nieustalony': np.nan,
    'Zawód miłosny': 'HeartBreak',
    'Leczony(a) psychiatrycznie': 'MentalHealth',
    'Nieporozumienie rodzinne/przemoc w rodzinie': 'FamilyConflict',
    'Nosiciel wirusa HIV, chory na AIDS': 'HealthLoss',
    'Nagła utrata źródła utrzymania': 'Finances',
    'Złe warunki ekonomiczne/długi': 'Finances',
    'Choroba psychiczna/zaburzenia psychiczne': 'MentalHealth',
    'Problemy w szkole lub pracy': 'SchoolWork',
    'Śmierć bliskiej osoby': 'CloseDeath',
    'Dokonanie przestępstwa lub wykroczenia': 'Crime',
    'Trwałe kalectwo': 'Disability',
    'Niepożądana ciąża': 'Other',
    'Choroba fizyczna': 'HealthLoss',
    'Pogorszenie lub nagła utrata zdrowia': 'HealthLoss',
    'Konflikt z osobami spoza rodziny': 'SchoolWork',
    'Zagrożenie lub utrata miejsca zamieszkania': 'Finances',
    'Mobbing, cybermobbing, znęcanie': 'SchoolWork',
    'Inny niewymieniony powyżej': 'Other'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Context'}, inplace=True)

###Powód_zamachu_2

In [182]:
column = 'Powód_zamachu_2'
mapping = {
    'Nieustalony': np.nan,
    'Zawód miłosny': 'HeartBreak',
    'Leczony(a) psychiatrycznie': 'MentalHealth',
    'Nieporozumienie rodzinne/przemoc w rodzinie': 'FamilyConflict',
    'Nosiciel wirusa HIV, chory na AIDS': 'HealthLoss',
    'Nagła utrata źródła utrzymania': 'Finances',
    'Złe warunki ekonomiczne/długi': 'Finances',
    'Choroba psychiczna/zaburzenia psychiczne': 'MentalHealth',
    'Problemy w szkole lub pracy': 'SchoolWork',
    'Śmierć bliskiej osoby': 'CloseDeath',
    'Dokonanie przestępstwa lub wykroczenia': 'Crime',
    'Trwałe kalectwo': 'Disability',
    'Niepożądana ciąża': 'Other',
    'Choroba fizyczna': 'HealthLoss',
    'Pogorszenie lub nagła utrata zdrowia': 'HealthLoss',
    'Konflikt z osobami spoza rodziny': 'SchoolWork',
    'Zagrożenie lub utrata miejsca zamieszkania': 'Finances',
    'Mobbing, cybermobbing, znęcanie': 'SchoolWork',
    'Inny niewymieniony powyżej': 'Other'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Context2'}, inplace=True)

###Powód_zamachu_3

In [183]:
column = 'Powód_zamachu_3'
mapping = {
    'Nieustalony': np.nan,
    'Zawód miłosny': 'HeartBreak',
    'Leczony(a) psychiatrycznie': 'MentalHealth',
    'Nieporozumienie rodzinne/przemoc w rodzinie': 'FamilyConflict',
    'Nosiciel wirusa HIV, chory na AIDS': 'HealthLoss',
    'Nagła utrata źródła utrzymania': 'Finances',
    'Złe warunki ekonomiczne/długi': 'Finances',
    'Choroba psychiczna/zaburzenia psychiczne': 'MentalHealth',
    'Problemy w szkole lub pracy': 'SchoolWork',
    'Śmierć bliskiej osoby': 'CloseDeath',
    'Dokonanie przestępstwa lub wykroczenia': 'Crime',
    'Trwałe kalectwo': 'Disability',
    'Niepożądana ciąża': 'Other',
    'Choroba fizyczna': 'HealthLoss',
    'Pogorszenie lub nagła utrata zdrowia': 'HealthLoss',
    'Konflikt z osobami spoza rodziny': 'SchoolWork',
    'Zagrożenie lub utrata miejsca zamieszkania': 'Finances',
    'Mobbing, cybermobbing, znęcanie': 'SchoolWork',
    'Inny niewymieniony powyżej': 'Other'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Context3'}, inplace=True)

###Powód_zamachu_4

In [184]:
column = 'Powód_zamachu_4'
mapping = {
    'Nieustalony': np.nan,
    'Zawód miłosny': 'HeartBreak',
    'Leczony(a) psychiatrycznie': 'MentalHealth',
    'Nieporozumienie rodzinne/przemoc w rodzinie': 'FamilyConflict',
    'Nosiciel wirusa HIV, chory na AIDS': 'HealthLoss',
    'Nagła utrata źródła utrzymania': 'Finances',
    'Złe warunki ekonomiczne/długi': 'Finances',
    'Choroba psychiczna/zaburzenia psychiczne': 'MentalHealth',
    'Problemy w szkole lub pracy': 'SchoolWork',
    'Śmierć bliskiej osoby': 'CloseDeath',
    'Dokonanie przestępstwa lub wykroczenia': 'Crime',
    'Trwałe kalectwo': 'Disability',
    'Niepożądana ciąża': 'Other',
    'Choroba fizyczna': 'HealthLoss',
    'Pogorszenie lub nagła utrata zdrowia': 'HealthLoss',
    'Konflikt z osobami spoza rodziny': 'SchoolWork',
    'Zagrożenie lub utrata miejsca zamieszkania': 'Finances',
    'Mobbing, cybermobbing, znęcanie': 'SchoolWork',
    'Inny niewymieniony powyżej': 'Other'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Context4'}, inplace=True)

In [185]:
list(set(df_raw_2023['Context'].unique()) | set(df_raw_2023['Context2'].unique()) | set(df_raw_2023['Context3'].unique()) | set(df_raw_2023['Context4'].unique()))

['CloseDeath',
 'Finances',
 nan,
 'FamilyConflict',
 'Disability',
 'Crime',
 'SchoolWork',
 'MentalHealth',
 'Other',
 'HeartBreak',
 'HealthLoss']

###Stan_świadomości

In [186]:
df_raw_2023['Stan_świadomości_*'].unique()

array(['Pod wpływem alkoholu', 'Brak danych/nieustalony', 'Trzeźwy(a)',
       'Pod wpływem leków', 'Pod wpływem alkoholu i środków odurzających',
       'Pod wpływem alkoholu i leków', 'Pod wpływem środków odurzających',
       'Pod wpływem alkoholu, leków i środków odurzających',
       'Pod wpływem zastępczych środków/substancji (dopalaczy)',
       'Pod wpływem alkoholu i zastępczych środków/substancji (dopalaczy)',
       'Pod wpływem leków i środków odurzających',
       'Pod wpływem alkoholu zastępczych środków/substancji (dopalaczy)',
       'Pod wpływem leków i srodków odurzających', nan], dtype=object)

In [187]:
column = 'Stan_świadomości_*'
mapping = {
    'Brak danych/nieustalony': np.nan,
    'Trzeźwy(a)': 'Sober',
    'Pod wpływem alkoholu': 'Alco',
    'Pod wpływem zastępczych środków/substancji (dopalaczy)': 'OtherSub',
    'Pod wpływem leków': 'OtherSub',
    'Pod wpływem środków odurzających': 'OtherSub',
    'Pod wpływem alkoholu i zastępczych środków/substancji (dopalaczy)': 'Alco&OtherSub',
    'Pod wpływem alkoholu zastępczych środków/substancji (dopalaczy)': 'Alco&OtherSub',
    'Pod wpływem alkoholu i leków': 'Alco&OtherSub',
    'Pod wpływem alkoholu i środków odurzających': 'Alco&OtherSub',
    'Pod wpływem leków i środków odurzających': 'OtherSub',
    'Pod wpływem alkoholu, leków i środków odurzających': 'Alco&OtherSub'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'Substance'}, inplace=True)

In [188]:
df_raw_2023['Substance'].unique()

array(['Alco', nan, 'Sober', 'OtherSub', 'Alco&OtherSub'], dtype=object)

###Informacje_dotyczące_leczenia_z_powodu_alkoholizmu/narkomanii

In [189]:
df_raw_2023['Informacje_dotyczące_leczenia_z_powodu_alkoholizmu/narkomanii'].unique()

array([nan, 'Nadużywał(a) alkoholu', 'Leczony(a) z powodu alkoholizmu',
       'Leczony(a) z powodu narkomanii',
       'Leczony(a) z powodu alkoholizmu i narkomanii',
       'Leczony(a) psychiatrycznie'], dtype=object)

In [190]:
column = 'Informacje_dotyczące_leczenia_z_powodu_alkoholizmu/narkomanii'
mapping = {
    'Leczony(a) psychiatrycznie': np.nan,
    'Nadużywał(a) alkoholu': 'Alco',
    'Leczony(a) z powodu alkoholizmu': 'Alco',
    'Leczony(a) z powodu narkomanii': 'OtherSub',
    'Leczony(a) z powodu alkoholizmu i narkomanii': 'Alco&OtherSub'
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)
df_raw_2023.rename(columns={column: 'AbuseInfo'}, inplace=True)

In [191]:
df_raw_2023['AbuseInfo'].unique()

array([nan, 'Alco', 'OtherSub', 'Alco&OtherSub'], dtype=object)

In [192]:
df_raw_2023['Informacje_dotyczące_stanu_zdrowia_*'].unique()

array(['Brak danych/nieustalono', 'Nadużywał(a) alkoholu',
       'Leczony(a) psychiatrycznie', 'Leczony(a) z powodu alkoholizmu',
       'Choroba fizyczna', 'Trwałe kalectwo',
       'Zatrzymany(a) w izbie wytrzeźwień', 'Używał narkotyków',
       'Nadużywał(a) alkoholu i narkotyków',
       'Nadużywał(a) alkoholu i nakrotyków',
       'Leczony(a) z powodu narkomanii', 'Używał dopalaczy i narkotyków',
       'Nadużywał(a) alkoholu i narkotykó',
       'Nadużywał(a) alkoholu, dopalaczy i narkotyków',
       'Nadużywał(a) alkoholu, narkotyków i dopalaczy',
       'Nadużywał(a) alkoholu i dopalaczy', 'Używał dopalaczy',
       'Nadużywał(a) alkoholu, dopalaczy, narkotyków',
       'Leczony(a) psychiatrycznie, nadużywał(a) alkoholu', nan],
      dtype=object)

In [193]:
column = 'Informacje_dotyczące_stanu_zdrowia_*'
mapping = {
    'Brak danych/nieustalono': np.nan,
    'Nadużywał(a) alkoholu': 'Alco',
    'Leczony(a) psychiatrycznie': np.nan,
    'Leczony(a) z powodu alkoholizmu': 'Alco',
    'Choroba fizyczna': np.nan,
    'Trwałe kalectwo': np.nan,
    'Zatrzymany(a) w izbie wytrzeźwień': 'Alco',
    'Nadużywał(a) alkoholu i narkotyków': 'Alco&OtherSub',
    'Nadużywał(a) alkoholu i nakrotyków': 'Alco&OtherSub',
    'Leczony(a) z powodu narkomanii': 'OtherSub',
    'Używał dopalaczy i narkotyków': 'OtherSub',
    'Nadużywał(a) alkoholu i narkotykó': 'OtherSub',
    'Nadużywał(a) alkoholu, dopalaczy i narkotyków': 'Alco&OtherSub',
    'Nadużywał(a) alkoholu, narkotyków i dopalaczy': 'Alco&OtherSub',
    'Nadużywał(a) alkoholu i dopalaczy': 'Alco&OtherSub',
    'Używał dopalaczy': 'OtherSub',
    'Nadużywał(a) alkoholu, dopalaczy, narkotyków': 'Alco&OtherSub',
    'Leczony(a) psychiatrycznie, nadużywał(a) alkoholu': 'Alco',
}

df_raw_2023[column] = df_raw_2023[column].map(mapping)

In [194]:
df_raw_2023['AbuseInfo'] = df_raw_2023['AbuseInfo'].fillna(df_raw_2023['Informacje_dotyczące_stanu_zdrowia_*'])
df_raw_2023.drop(columns='Informacje_dotyczące_stanu_zdrowia_*', inplace=True)

##Powód zamachu - dummies

In [195]:
columns_to_drop = ['Context', 'Context2', 'Context3', 'Context4']
df_powód_zamachu_2023 = df_raw_2023[columns_to_drop]
df_raw_2023.drop(columns=columns_to_drop, inplace=True)


In [196]:
powód_zamachu_values = (
    set(df_powód_zamachu_2023['Context'].unique()) |
    set(df_powód_zamachu_2023['Context2'].unique()) |
    set(df_powód_zamachu_2023['Context3'].unique()) |
    set(df_powód_zamachu_2023['Context4'].unique())
)

In [197]:
powód_zamachu_values

{'CloseDeath',
 'Crime',
 'Disability',
 'FamilyConflict',
 'Finances',
 'HealthLoss',
 'HeartBreak',
 'MentalHealth',
 'Other',
 'SchoolWork',
 nan}

In [198]:
for value in powód_zamachu_values:
    column_name = 'Context_' + str(value)
    df_powód_zamachu_2023[column_name] = df_powód_zamachu_2023.apply(lambda row: 1 if value in row.values else 0, axis=1)


<ipython-input-198-2ae7b8e01b52>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_powód_zamachu_2023[column_name] = df_powód_zamachu_2023.apply(lambda row: 1 if value in row.values else 0, axis=1)
<ipython-input-198-2ae7b8e01b52>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_powód_zamachu_2023[column_name] = df_powód_zamachu_2023.apply(lambda row: 1 if value in row.values else 0, axis=1)
<ipython-input-198-2ae7b8e01b52>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice fr

In [199]:
columns_to_drop = ['Context', 'Context2', 'Context3', 'Context4', 'Context_nan']
df_powód_zamachu_2023.drop(columns=columns_to_drop, inplace=True)


<ipython-input-199-1efdf2541b49>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_powód_zamachu_2023.drop(columns=columns_to_drop, inplace=True)


In [200]:
df_powód_zamachu_2023.head(5)

Context_CloseDeath  Context_Finances  Context_FamilyConflict  \
0                   0                 0                       1   
1                   0                 0                       0   
2                   0                 0                       1   
3                   0                 0                       1   
4                   0                 0                       0   

   Context_Disability  Context_Crime  Context_SchoolWork  \
0                   0              0                   0   
1                   0              0                   0   
2                   0              0                   0   
3                   0              0                   0   
4                   0              0                   1   

   Context_MentalHealth  Context_Other  Context_HeartBreak  Context_HealthLoss  
0                     0              1                   0                   0  
1                     0              0                   0                   0  
2                     0              0                   0                   0  
3                     0              0                   0                   0  
4                     0              0                   0                   0

##Liczba_powodów_zamachu

In [201]:
df_raw_2023['CountContext'] = df_powód_zamachu_2023.sum(axis=1)

In [202]:
df_raw_2023.head(5)

ID_samobójcy     Date   Age1 Gender     Marital Education    WorkInfo  \
0    138421942  01.2023  25-29      M  Cohabitant       NaN  Unemployed   
1    138421944  01.2023  55-59      M     Married       NaN         NaN   
2    138421949  01.2023  13-18      F     Single        NaN     Student   
3    138421953  01.2023  55-59      M     Married       NaN         NaN   
4    138421954  01.2023  19-24      F  Cohabitant       NaN         NaN   

      Income  Fatal  Place                           Klasa_miejscowości  \
0        NaN    0.0  House                                         Wieś   
1        NaN    0.0  House    Miasto o liczbie ludności 20 000 – 49 999   
2  Dependent    0.0  House                                         Wieś   
3        NaN    0.0  House          Miasto o liczbie ludności do 19 999   
4        NaN    0.0  House  Miasto o liczbie ludności 100 000 – 499 999   

      Method Substance AbuseInfo  \
0  Self-harm      Alco       NaN   
1    Hanging       NaN       NaN   
2      Drugs     Sober       NaN   
3  Self-harm      Alco      Alco   
4      Drugs      Alco      Alco   

  W_ciągu_ostatniego_miesiąca_sprawca_zdarzenia_miał_przynajmniej_jeden_raz_kontakt_z_*  \
0                          Brak możliwości ustalenia                                      
1                          Brak możliwości ustalenia                                      
2                                 Placówką leczniczą                                      
3                          Brak możliwości ustalenia                                      
4                          Brak możliwości ustalenia                                      

  DateY DateM   Age2  CountContext  
0  2023    01  19-34             2  
1  2023    01  35-64             0  
2  2023    01  00-18             1  
3  2023    01  35-64             1  
4  2023    01  19-34             1

# 2013_2022

In [203]:
df_raw_2013_2022 = pd.read_csv('https://raw.githubusercontent.com/Hubert26/suicides_IPPAN/main/data/final_samobojstwa_2013_2022.csv', delimiter=',', low_memory=False)

In [204]:
df_raw_2013_2022.head(5)

ID samobójcy Data raportu [RRRRMM]  Przedział wiekowy  Płeć  Stan cywilny  \
0  114581552,00                201301                  0     2             0   
1  114584284,00                201301                  2     2             0   
2  114584293,00                201301                  2     1             1   
3  114584312,00                201301                  3     2             1   
4  114584399,00                201301                  7     2             1   

   Wykształcenie  Informacje o pracy i nauce  Źródło utrzymania  \
0              0                           0                  0   
1              0                           1                  0   
2              2                           1                  1   
3              0                           0                  0   
4              0                           9                  0   

   Czy samobójstwo zakończyło się zgonem  Miejsce zamachu  Sposób popełnienia  \
0                                      0                0                   0   
1                                      1                1                   1   
2                                      1               15                   2   
3                                      1                0                  18   
4                                      1                2                   3   

   Powód zamachu Powód zamachu 2  Powód zamachu 3  Powód zamachu 4  \
0              0             NaN              NaN              NaN   
1              0             NaN              NaN              NaN   
2              0             NaN              NaN              NaN   
3              1             NaN              NaN              NaN   
4              0             NaN              NaN              NaN   

   Stan świadomości  Informacje o używaniu substancji  \
0                 0                                 0   
1                 0                                 0   
2                 0                                 0   
3                 0                                 0   
4                 2                                 0   

   Informacje dotyczące leczenia z powodu alkoholizmu/narkomanii  
0                                                  0              
1                                                  0              
2                                                  0              
3                                                  0              
4                                                  0

##Zamiana nazw kolumn

In [205]:
# Zamiana spacji na podkreślenia w nazwach kolumn
df_raw_2013_2022.rename(columns=lambda x: x.replace(' ', '_'), inplace=True)


In [206]:
df_raw_2013_2022.rename(columns={'Data_raportu_[RRRRMM]': 'Date'}, inplace=True)

## Daty

In [207]:
# Wyodrębnienie roku i miesiąca
df_raw_2013_2022['DateY'] = df_raw_2013_2022['Date'].apply(lambda x: x[0:4] if len(x) > 8 else x[:4])
df_raw_2013_2022['DateM'] = df_raw_2013_2022['Date'].apply(lambda x: x[5:7] if len(x) > 8 else x[4:6])

In [208]:
df_raw_2013_2022['DateY'].unique()

array(['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022'], dtype=object)

In [209]:
df_raw_2013_2022['DateM'].unique()

array(['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11',
       '12'], dtype=object)

In [210]:
# Połączenie roku i miesiąca w formacie MM.YYYY
df_raw_2013_2022['Date'] = df_raw_2013_2022['DateM'] + '.' + df_raw_2013_2022['DateY']

In [211]:
df_raw_2013_2022['Date'].unique()

array(['01.2013', '02.2013', '03.2013', '04.2013', '05.2013', '06.2013',
       '07.2013', '08.2013', '09.2013', '10.2013', '11.2013', '12.2013',
       '01.2014', '02.2014', '03.2014', '04.2014', '05.2014', '06.2014',
       '07.2014', '08.2014', '09.2014', '10.2014', '11.2014', '12.2014',
       '01.2015', '02.2015', '03.2015', '04.2015', '05.2015', '06.2015',
       '07.2015', '08.2015', '09.2015', '10.2015', '11.2015', '12.2015',
       '01.2016', '02.2016', '03.2016', '04.2016', '05.2016', '06.2016',
       '07.2016', '08.2016', '09.2016', '10.2016', '11.2016', '12.2016',
       '01.2017', '02.2017', '03.2017', '04.2017', '05.2017', '06.2017',
       '07.2017', '08.2017', '09.2017', '10.2017', '11.2017', '12.2017',
       '01.2018', '02.2018', '03.2018', '04.2018', '05.2018', '06.2018',
       '07.2018', '08.2018', '09.2018', '10.2018', '11.2018', '12.2018',
       '01.2019', '02.2019', '03.2019', '04.2019', '05.2019', '06.2019',
       '07.2019', '08.2019', '09.2019', '10.2019', 

##Mapowanie

###Przedział_wiekowy

In [212]:
column = 'Przedział_wiekowy'
mapping = {
    0: np.nan,
    1: '07-12',
    2: '13-18',
    3: '19-24',
    4: '25-29',
    5: '30-34',
    6: '35-39',
    7: '40-44',
    8: '45-49',
    9: '50-54',
    10: '55-59',
    11: '60-64',
    12: '65-69',
    13: '70-74',
    14: '75-79',
    15: '80-84',
    16: '85+'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Age1'}, inplace=True)

In [213]:
df_raw_2013_2022['Age2']=df_raw_2013_2022['Age1']

In [214]:
column = 'Age2'
mapping = {
    "07-12": '00-18',
    '13-18': '00-18',
    '19-24': '19-34',
    '25-29': '19-34',
    '30-34': '19-34',
    '35-39': '35-64',
    '40-44': '35-64',
    '45-49': '35-64',
    '50-54': '35-64',
    '55-59': '35-64',
    '60-64': '35-64',
    '65-69': '65+',
    '70-74': '65+',
    '75-79': '65+',
    '80-84': '65+',
    '85+': '65+'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)


In [215]:
df_raw_2013_2022['Age2'].unique()

array([nan, '00-18', '19-34', '35-64', '65+'], dtype=object)

###Płeć

In [216]:
column = 'Płeć'
mapping = {
    0: np.nan,
    1: 'F',
    2: 'M'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Gender'}, inplace=True)

In [217]:
df_raw_2013_2022['Gender'].unique()

array(['M', 'F', nan], dtype=object)

###Stan_cywilny

In [218]:
column = 'Stan_cywilny'
mapping = {
    0: np.nan,
    1: 'Single',
    2: 'Cohabitant',
    3: 'Married',
    4: 'Separated',
    5: 'Divorced',
    6: 'Widowed'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Marital'}, inplace=True)


In [219]:
df_raw_2013_2022['Marital'].unique()

array([nan, 'Single', 'Married', 'Cohabitant', 'Widowed', 'Separated',
       'Divorced'], dtype=object)

###Wykształcenie

In [220]:
column = 'Wykształcenie'
mapping = {
    0: np.nan,
    1: 'Pre-primary',
    2: 'Primary',
    3: 'Secondary',
    4: 'Vocational',
    5: 'Secondary',
    6: 'Secondary',
    7: 'Higher'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Education'}, inplace=True)



In [221]:
df_raw_2013_2022['Education'].unique()

array([nan, 'Primary', 'Vocational', 'Higher', 'Secondary', 'Pre-primary'],
      dtype=object)

###Informacje_o_pracy_i_nauce

In [222]:
column = 'Informacje_o_pracy_i_nauce'
mapping = {
    0: np.nan,
    1: 'Student',
    2: 'Student',
    3: 'Employed',
    4: 'Employed',
    5: 'Agriculturalist',
    6: 'Employed',
    7: 'Employed',
    8: 'Employed',
    9: 'Unemployed'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'WorkInfo'}, inplace=True)

In [223]:
df_raw_2013_2022['WorkInfo'].unique()

array([nan, 'Student', 'Unemployed', 'Employed', 'Agriculturalist'],
      dtype=object)

###Źródło_utrzymania

In [224]:
column = 'Źródło_utrzymania'
mapping = {
    0: np.nan,  # Zamiana 0 na NaN
    1: 'Dependent',
    2: 'Steady',
    3: 'Benefits',
    4: 'NoSteady'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Income'}, inplace=True)

In [225]:
df_raw_2013_2022['Income'].unique()

array([nan, 'Dependent', 'NoSteady', 'Steady', 'Benefits'], dtype=object)

###Czy_samobójstwo_zakończyło_się_zgonem

In [226]:
column = 'Czy_samobójstwo_zakończyło_się_zgonem'

mapping = {
    0: np.nan,  # Zamiana 0 na NaN
    1: 1,
    2: 0
}
df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Fatal'}, inplace=True)

In [227]:
df_raw_2013_2022['Fatal'].unique()

array([nan,  1.,  0.])

###Miejsce_zamachu

In [228]:
column = 'Miejsce_zamachu'
mapping = {
    0: np.nan,
    1: 'Road',
    2: 'UtilitySpaces',
    3: 'House',
    4: 'Railway',
    5: 'Forest',
    6: 'House',
    7: 'WaterRes',
    8: 'Work',
    9: 'Institution',
    10: 'Isolation',
    11: 'PoliceArmy',
    12: 'Institution',
    13: 'School',
    14: 'PoliceArmy',
    15: 'Other'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Place'}, inplace=True)


In [229]:
df_raw_2013_2022['Place'].unique()

array([nan, 'Road', 'Other', 'UtilitySpaces', 'House', 'Railway',
       'Forest', 'WaterRes', 'Work', 'Institution', 'Isolation',
       'PoliceArmy', 'School'], dtype=object)

###Sposób_popełnienia

In [230]:
column = 'Sposób_popełnienia'
mapping = {
    0: np.nan,
    1: 'Vehicle',
    2: 'Jumping',
    3: 'Hanging',
    4: 'Self-harm',
    5: 'Schooting',
    6: 'Self-harm',
    7: 'Self-harm',
    8: 'Drugs',
    9: 'Poisoning',
    10: 'Gas',
    11: 'Drugs',
    12: 'Poisoning',
    13: 'Drugs',
    14: 'Drugs',
    15: 'Drowning',
    16: 'Self-harm',
    17: 'Other',
    18: 'Other'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Method'}, inplace=True)

In [231]:
df_raw_2013_2022['Method'].unique()

array([nan, 'Vehicle', 'Jumping', 'Other', 'Hanging', 'Self-harm',
       'Schooting', 'Drugs', 'Poisoning', 'Gas', 'Drowning'], dtype=object)

###Powód_zamachu

In [232]:
column = 'Powód_zamachu'
mapping = {
    0: np.nan,
    1: 'HeartBreak',
    2: 'MentalHealth',
    3: 'FamilyConflict',
    4: 'HealthLoss',
    5: 'Finances',
    6: 'Finances',
    7: 'HealthLoss',
    8: 'SchoolWork',
    9: 'CloseDeath',
    10: 'Crime',
    11: 'Disability',
    12: 'Other',
    13: 'HealthLoss',
    14: 'HealthLoss',
    15: 'SchoolWork',
    16: 'Finances',
    17: 'SchoolWork',
    18: 'Other'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Context'}, inplace=True)

In [233]:
df_raw_2013_2022['Context'].unique()

array([nan, 'HeartBreak', 'Other', 'MentalHealth', 'FamilyConflict',
       'HealthLoss', 'Finances', 'SchoolWork', 'CloseDeath', 'Crime',
       'Disability'], dtype=object)

###Powód_zamachu_2

In [234]:
column = 'Powód_zamachu_2'
mapping = {
    0: np.nan,
    1: 'HeartBreak',
    2: 'MentalHealth',
    3: 'FamilyConflict',
    4: 'HealthLoss',
    5: 'Finances',
    6: 'Finances',
    7: 'HealthLoss',
    8: 'SchoolWork',
    9: 'CloseDeath',
    10: 'Crime',
    11: 'Disability',
    12: 'Other',
    13: 'HealthLoss',
    14: 'HealthLoss',
    15: 'SchoolWork',
    16: 'Finances',
    17: 'SchoolWork',
    18: 'Other'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Context2'}, inplace=True)

In [235]:
df_raw_2013_2022['Context2'].unique()

array([nan], dtype=object)

###Powód_zamachu_3

In [236]:
column = 'Powód_zamachu_3'
mapping = {
    0: np.nan,
    1: 'HeartBreak',
    2: 'MentalHealth',
    3: 'FamilyConflict',
    4: 'HealthLoss',
    5: 'Finances',
    6: 'Finances',
    7: 'HealthLoss',
    8: 'SchoolWork',
    9: 'CloseDeath',
    10: 'Crime',
    11: 'Disability',
    12: 'Other',
    13: 'HealthLoss',
    14: 'HealthLoss',
    15: 'SchoolWork',
    16: 'Finances',
    17: 'SchoolWork',
    18: 'Other'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Context3'}, inplace=True)

In [237]:
df_raw_2013_2022['Context3'].unique()

array([nan, 'MentalHealth', 'Finances', 'CloseDeath', 'HeartBreak',
       'HealthLoss', 'Disability', 'SchoolWork', 'FamilyConflict',
       'Crime', 'Other'], dtype=object)

###Powód_zamachu_4

In [238]:
column = 'Powód_zamachu_4'
mapping = {
    0: np.nan,
    1: 'HeartBreak',
    2: 'MentalHealth',
    3: 'FamilyConflict',
    4: 'HealthLoss',
    5: 'Finances',
    6: 'Finances',
    7: 'HealthLoss',
    8: 'SchoolWork',
    9: 'CloseDeath',
    10: 'Crime',
    11: 'Disability',
    12: 'Other',
    13: 'HealthLoss',
    14: 'HealthLoss',
    15: 'SchoolWork',
    16: 'Finances',
    17: 'SchoolWork',
    18: 'Other'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Context4'}, inplace=True)

In [239]:
df_raw_2013_2022['Context4'].unique()

array([nan, 'MentalHealth', 'Finances', 'CloseDeath', 'HeartBreak',
       'SchoolWork', 'HealthLoss', 'Disability'], dtype=object)

###Stan_świadomości

In [240]:
column = 'Stan_świadomości'
mapping = {
    0: np.nan,
    1: 'Sober',
    2: 'Alco',
    3: 'OtherSub',
    4: 'OtherSub',
    5: 'OtherSub',
    6: 'OtherSub',
    7: 'Alco&OtherSub',
    8: 'Alco&OtherSub',
    9: 'Alco&OtherSub',
    10: 'Alco&OtherSub',
    11: 'Alco&OtherSub',
    12: 'OtherSub',
    13: 'OtherSub',
    14: 'OtherSub',
    15: 'OtherSub',
    16: 'OtherSub',
    17: 'Alco&OtherSub',
    18: 'Alco&OtherSub'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'Substance'}, inplace=True)

In [241]:
df_raw_2013_2022['Substance'].unique()

array([nan, 'Alco', 'Sober', 'OtherSub', 'Alco&OtherSub'], dtype=object)

###Informacje_o_używaniu_substancji

In [242]:
column = 'Informacje_o_używaniu_substancji'
mapping = {
    0: np.nan,
    1: 'Alco',
    2: 'OtherSub',
    3: 'OtherSub',
    4: 'Alco&OtherSub',
    5: 'OtherSub',
    6: 'Alco&OtherSub',
    7: 'Alco&OtherSub'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)
df_raw_2013_2022.rename(columns={column: 'AbuseInfo'}, inplace=True)


In [243]:
df_raw_2013_2022['AbuseInfo'].unique()

array([nan, 'Alco', 'OtherSub', 'Alco&OtherSub'], dtype=object)

###Informacje_dotyczące_leczenia_z_powodu_alkoholizmu/narkomanii

In [244]:
column = 'Informacje_dotyczące_leczenia_z_powodu_alkoholizmu/narkomanii'
mapping = {
    0: np.nan,
    1: 'Alco',
    2: 'OtherSub',
    3: 'Alco&OtherSub'
}

df_raw_2013_2022[column] = df_raw_2013_2022[column].map(mapping)


In [245]:
df_raw_2013_2022['Informacje_dotyczące_leczenia_z_powodu_alkoholizmu/narkomanii'].unique()

array([nan, 'Alco', 'OtherSub', 'Alco&OtherSub'], dtype=object)

In [246]:
df_raw_2013_2022['AbuseInfo'] = df_raw_2013_2022['AbuseInfo'].fillna(df_raw_2013_2022['Informacje_dotyczące_leczenia_z_powodu_alkoholizmu/narkomanii'])
df_raw_2013_2022.drop(columns='Informacje_dotyczące_leczenia_z_powodu_alkoholizmu/narkomanii', inplace=True)

##Powód zamachu - dummies

In [247]:
columns_to_drop = ['Context', 'Context2', 'Context3', 'Context4']
df_powód_zamachu_2013_2022 = df_raw_2013_2022[columns_to_drop]
df_raw_2013_2022.drop(columns=columns_to_drop, inplace=True)


In [248]:
powód_zamachu_values = (
    set(df_powód_zamachu_2013_2022['Context'].unique()) |
    set(df_powód_zamachu_2013_2022['Context2'].unique()) |
    set(df_powód_zamachu_2013_2022['Context3'].unique()) |
    set(df_powód_zamachu_2013_2022['Context4'].unique())
)

In [249]:
powód_zamachu_values

{'CloseDeath',
 'Crime',
 'Disability',
 'FamilyConflict',
 'Finances',
 'HealthLoss',
 'HeartBreak',
 'MentalHealth',
 'Other',
 'SchoolWork',
 nan}

In [250]:
for value in powód_zamachu_values:
    column_name = 'Context_' + str(value)
    df_powód_zamachu_2013_2022[column_name] = df_powód_zamachu_2013_2022.apply(lambda row: 1 if value in row.values else 0, axis=1)


<ipython-input-250-0e5087bd058e>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_powód_zamachu_2013_2022[column_name] = df_powód_zamachu_2013_2022.apply(lambda row: 1 if value in row.values else 0, axis=1)
<ipython-input-250-0e5087bd058e>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_powód_zamachu_2013_2022[column_name] = df_powód_zamachu_2013_2022.apply(lambda row: 1 if value in row.values else 0, axis=1)
<ipython-input-250-0e5087bd058e>:3: SettingWithCopyWarning: 
A value is trying to be set on 

In [251]:
columns_to_drop = ['Context', 'Context2', 'Context3', 'Context4', 'Context_nan']
df_powód_zamachu_2013_2022.drop(columns=columns_to_drop, inplace=True)


<ipython-input-251-9a2200cc8667>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_powód_zamachu_2013_2022.drop(columns=columns_to_drop, inplace=True)


##Liczba_powodów_zamachu

In [252]:
df_raw_2013_2022['CountContext'] = df_powód_zamachu_2013_2022.sum(axis=1)

In [253]:
df_raw_2013_2022.head(5)

ID_samobójcy     Date   Age1 Gender Marital Education    WorkInfo  \
0  114581552,00  01.2013    NaN      M     NaN       NaN         NaN   
1  114584284,00  01.2013  13-18      M     NaN       NaN     Student   
2  114584293,00  01.2013  13-18      F  Single   Primary     Student   
3  114584312,00  01.2013  19-24      M  Single       NaN         NaN   
4  114584399,00  01.2013  40-44      M  Single       NaN  Unemployed   

      Income  Fatal          Place   Method Substance AbuseInfo DateY DateM  \
0        NaN    NaN            NaN      NaN       NaN       NaN  2013    01   
1        NaN    1.0           Road  Vehicle       NaN       NaN  2013    01   
2  Dependent    1.0          Other  Jumping       NaN       NaN  2013    01   
3        NaN    1.0            NaN    Other       NaN       NaN  2013    01   
4        NaN    1.0  UtilitySpaces  Hanging      Alco       NaN  2013    01   

    Age2  CountContext  
0    NaN             0  
1  00-18             0  
2  00-18             0  
3  19-34             1  
4  35-64             0

#Scalenie

##df_raw

In [254]:
# Znajdź wspólne kolumny
common_columns = list(set(df_raw_2023.columns) & set(df_raw_2013_2022.columns))

# Wybierz wspólne kolumny z obu DataFrame'ów
df_raw_2023_selected = df_raw_2023[common_columns]
df_raw_2013_2022_selected = df_raw_2013_2022[common_columns]

# Połącz oba DataFrame'y
df_raw = pd.concat([df_raw_2013_2022_selected, df_raw_2023_selected])


In [255]:
df_raw.head(1)

Income Age1  Fatal Method DateM Gender Education AbuseInfo DateY  \
0    NaN  NaN    NaN    NaN    01      M       NaN       NaN  2013   

   ID_samobójcy WorkInfo Substance Age2     Date Place  CountContext Marital  
0  114581552,00      NaN       NaN  NaN  01.2013   NaN             0     NaN

In [256]:
df_raw.shape

(128332, 17)

In [257]:
df_raw_2013_2022.head(1)

ID_samobójcy     Date Age1 Gender Marital Education WorkInfo Income  Fatal  \
0  114581552,00  01.2013  NaN      M     NaN       NaN      NaN    NaN    NaN   

  Place Method Substance AbuseInfo DateY DateM Age2  CountContext  
0   NaN    NaN       NaN       NaN  2013    01  NaN             0

In [258]:
df_raw_2013_2022.shape

(113196, 17)

In [259]:
df_raw_2023.head(1)

ID_samobójcy     Date   Age1 Gender     Marital Education    WorkInfo  \
0    138421942  01.2023  25-29      M  Cohabitant       NaN  Unemployed   

  Income  Fatal  Place Klasa_miejscowości     Method Substance AbuseInfo  \
0    NaN    0.0  House               Wieś  Self-harm      Alco       NaN   

  W_ciągu_ostatniego_miesiąca_sprawca_zdarzenia_miał_przynajmniej_jeden_raz_kontakt_z_*  \
0                          Brak możliwości ustalenia                                      

  DateY DateM   Age2  CountContext  
0  2023    01  19-34             2

In [260]:
df_raw_2023.shape

(15136, 19)

In [261]:
df_raw['DateY'].unique()

array(['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023', nan], dtype=object)

In [262]:
df_raw['DateM'].unique()

array(['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11',
       '12', nan], dtype=object)

In [263]:
df_raw['Date'].unique()

array(['01.2013', '02.2013', '03.2013', '04.2013', '05.2013', '06.2013',
       '07.2013', '08.2013', '09.2013', '10.2013', '11.2013', '12.2013',
       '01.2014', '02.2014', '03.2014', '04.2014', '05.2014', '06.2014',
       '07.2014', '08.2014', '09.2014', '10.2014', '11.2014', '12.2014',
       '01.2015', '02.2015', '03.2015', '04.2015', '05.2015', '06.2015',
       '07.2015', '08.2015', '09.2015', '10.2015', '11.2015', '12.2015',
       '01.2016', '02.2016', '03.2016', '04.2016', '05.2016', '06.2016',
       '07.2016', '08.2016', '09.2016', '10.2016', '11.2016', '12.2016',
       '01.2017', '02.2017', '03.2017', '04.2017', '05.2017', '06.2017',
       '07.2017', '08.2017', '09.2017', '10.2017', '11.2017', '12.2017',
       '01.2018', '02.2018', '03.2018', '04.2018', '05.2018', '06.2018',
       '07.2018', '08.2018', '09.2018', '10.2018', '11.2018', '12.2018',
       '01.2019', '02.2019', '03.2019', '04.2019', '05.2019', '06.2019',
       '07.2019', '08.2019', '09.2019', '10.2019', 

##df_powód_zamachu

In [264]:
# Połącz oba DataFrame'y
df_powód_zamachu = pd.concat([df_powód_zamachu_2013_2022, df_powód_zamachu_2023])
df_powód_zamachu.fillna(0, inplace=True)

In [265]:
df_powód_zamachu.head(1)

Context_Finances  Context_CloseDeath  Context_FamilyConflict  \
0                 0                   0                       0   

   Context_Disability  Context_HeartBreak  Context_Crime  Context_SchoolWork  \
0                   0                   0              0                   0   

   Context_MentalHealth  Context_Other  Context_HealthLoss  
0                     0              0                   0

In [266]:
df_powód_zamachu.shape

(128332, 10)

In [267]:
df_powód_zamachu_2013_2022.head(1)

Context_Finances  Context_CloseDeath  Context_FamilyConflict  \
0                 0                   0                       0   

   Context_Disability  Context_HeartBreak  Context_Crime  Context_SchoolWork  \
0                   0                   0              0                   0   

   Context_MentalHealth  Context_Other  Context_HealthLoss  
0                     0              0                   0

In [268]:
df_powód_zamachu_2013_2022.shape

(113196, 10)

In [269]:
df_powód_zamachu_2023.head(1)

Context_CloseDeath  Context_Finances  Context_FamilyConflict  \
0                   0                 0                       1   

   Context_Disability  Context_Crime  Context_SchoolWork  \
0                   0              0                   0   

   Context_MentalHealth  Context_Other  Context_HeartBreak  Context_HealthLoss  
0                     0              1                   0                   0

In [270]:
df_powód_zamachu_2023.shape

(15136, 10)

#Zapis

In [271]:
# from google.colab import drive
# drive.mount('/content/drive')
# df_raw.to_csv('/content/drive/My Drive/preped_samobojstwa_2013_2022.csv', index=False)
# df_powód_zamachu.to_csv('/content/drive/My Drive/preped_powod_zamachu_samobojstwa_2013_2022.csv', index=False)

In [272]:
df_powód_zamachu.shape

(128332, 10)

In [273]:
df_raw.shape

(128332, 17)

In [274]:
out_preped_suicides = pd.concat([df_raw, df_powód_zamachu], axis=1)

In [275]:
out_preped_suicides.shape

(128332, 27)

In [276]:
file_name = 'out_preped_suicides.csv'
out_preped_suicides.to_csv(file_name, index=False)
files.download(file_name)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>